# Site settings
title: "Longxiang Blog"
url: "https://wlongxiang.github.io"
author: "LongxiangWang"
email: "wlongxiang1119@gmail.com"
description: "A place to share my experiences and thoughts"
baseurl: ""

# Google analytics
google_analytics:
  provider : google
  google : 
      tracking_id : 'UA-48154886-1'
  getclicky :
    site_id :

# Optional features
animated:           false
show_related_posts: false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Social icons
show_social_icons: true
github_username: wlongxiang
stackoverflow_id:
twitter_username: wanglongxiang11
google_plus_id:
linkedin_username:wlongxiang
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: true
share_text: 'I always believe in sharing'
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: false
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false

# Build settings
markdown: kramdown
permalink:    pretty
paginate:     7 # this variable determines how many items should be displayed per page
sass:
  compressed: true
